spring:
  application:
    name: notification-service

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

server:
  port: 8090

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true